# Generated by Django 4.2.1 on 2023-05-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAFLDraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-full_name']},
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AddField(
            model_name='team',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
