# Generated by Django 4.2.1 on 2023-05-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAFLDraft', '0002_alter_owner_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='contract_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roster',
            name='position',
            field=models.CharField(choices=[('P', 'P'), ('C', 'C'), ('1B', '1B'), ('2B', '2B'), ('3B', '3B'), ('SS', 'SS'), ('OF', 'OF'), ('U', 'U')], max_length=2),
        ),
    ]
