# Generated by Django 4.2.1 on 2023-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAFLDraft', '0003_alter_roster_active_alter_roster_contract_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='username',
            field=models.CharField(default='', max_length=15),
        ),
    ]
