# Generated by Django 4.2.1 on 2023-05-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAFLDraft', '0004_owner_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('protection_lists_locked', models.BooleanField()),
            ],
        ),
    ]
