# Generated by Django 4.2.1 on 2024-01-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAFLDraft', '0005_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='adp',
            field=models.FloatField(default=9999),
        ),
        migrations.AddField(
            model_name='player',
            name='stat1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='stat2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='stat3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='stat4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='stat5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='stat6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
