# Generated by Django 4.2.1 on 2024-01-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAFLDraft', '0006_player_adp_player_stat1_player_stat2_player_stat3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
