# Generated by Django 4.2.1 on 2025-03-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAFLDraft', '0007_roster_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['adp', '-value']},
        ),
        migrations.AddField(
            model_name='player',
            name='inflatedvalue',
            field=models.FloatField(default=0, verbose_name='Inf Value'),
        ),
        migrations.AlterField(
            model_name='player',
            name='adp',
            field=models.FloatField(default=9999, verbose_name='ADP'),
        ),
        migrations.AlterField(
            model_name='player',
            name='stat1',
            field=models.FloatField(default=0, verbose_name='HR/Wins'),
        ),
        migrations.AlterField(
            model_name='player',
            name='stat2',
            field=models.FloatField(default=0, verbose_name='SB/Saves'),
        ),
        migrations.AlterField(
            model_name='player',
            name='stat3',
            field=models.FloatField(default=0, verbose_name='RBI/SO'),
        ),
        migrations.AlterField(
            model_name='player',
            name='stat4',
            field=models.FloatField(default=0, verbose_name='Runs/Holds'),
        ),
        migrations.AlterField(
            model_name='player',
            name='stat5',
            field=models.FloatField(default=0, verbose_name='AB/IP'),
        ),
        migrations.AlterField(
            model_name='player',
            name='stat6',
            field=models.FloatField(default=0, verbose_name='Hits/ER'),
        ),
        migrations.AlterField(
            model_name='player',
            name='value',
            field=models.FloatField(default=0, verbose_name='Value'),
        ),
    ]
